server:
  port: 8082
spring:
  application:
    name: mall-user-feign-demo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'